class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'English (US)': {
      // Navigation & Headers
      'live_session': 'Live Session',
      'student_profile': 'Student Profile',
      'ask_question': 'Ask a Question',
      'settings': 'Settings',
      'session': 'Session',
      'profile': 'Profile',
      'ask': 'Ask',
      'class_pulse': 'ClassPulse',
      // Join Class Screen
      'enter_code': 'Enter Class Code',
      'join_class': 'Join Class',
      'class_code': 'Class Code',
      'please_enter_code': 'Please enter a class code',
      'invalid_code': 'Invalid class code',
      // Live Session Screen
      'feedback': 'Feedback',
      'excellent': 'Excellent',
      'good': 'Good',
      'average': 'Average',
      'poor': 'Poor',
      'end_session': 'End Session',
      'how_was_session': 'How was the session?',
      'how_was_class': 'How was this class?',
      // Profile Screen
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone',
      'academic_year': 'Academic Year',
      'student_id': 'Student ID',
      'edit_profile': 'Edit Profile',
      'performance': 'Performance',
      'accuracy': 'Accuracy',
      'participation': 'Participation',
      'completion_rate': 'Completion Rate',
      'session_insights': 'Session Insights',
      'your_questions': 'Your Questions',
      'no_questions': 'No questions yet',
      'english': 'English',
      'math': 'Mathematics',
      'science': 'Science',
      'history': 'History',
      // Ask Question Screen
      'question_title': 'Question Title',
      'question_description': 'Question Description',
      'describe_your_question': 'Describe your question',
      // Settings & Dialogs
      'submit': 'Submit',
      'cancel': 'Cancel',
      'notifications': 'Notifications',
      'language': 'Language',
      'theme': 'Theme',
      'two_factor': 'Two-Factor Authentication',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'logout': 'Logout',
      'save': 'Save',
      'delete': 'Delete',
      'choose_theme': 'Choose Theme',
      'choose_language': 'Choose Language',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      // Messages & Status
      'theme_changed': 'Theme changed',
      'language_changed': 'Language changed',
      'notification_enabled': 'Notifications enabled',
      'notification_disabled': 'Notifications disabled',
      'profile_updated': 'Profile updated successfully',
      'password_changed': 'Password changed successfully',
      'storage_cleared': 'Storage cleared',
      'logged_out': 'Logged out successfully',
      // Account Settings
      'account_settings': 'Account Settings',
      'app_settings': 'App Settings',
      'profile_information': 'Profile Information',
      'edit_profile_details': 'Edit your profile details',
      'change_password': 'Change Password',
      'update_password': 'Update your password',
      'clear_cache': 'Clear Cache',
      'clear_app_storage': 'Clear app storage and cache',
      'about_app': 'About App',
      'version': 'Version 1.0.0',
    },
    'Spanish': {
      // Navigation & Headers
      'live_session': 'Sesión en Directo',
      'student_profile': 'Perfil del Estudiante',
      'ask_question': 'Hacer una Pregunta',
      'settings': 'Configuración',
      'session': 'Sesión',
      'profile': 'Perfil',
      'ask': 'Preguntar',
      'class_pulse': 'ClassPulse',
      // Join Class Screen
      'enter_code': 'Ingrese el Código de Clase',
      'join_class': 'Unirse a la Clase',
      'class_code': 'Código de Clase',
      'please_enter_code': 'Por favor ingrese un código de clase',
      'invalid_code': 'Código de clase inválido',
      // Live Session Screen
      'feedback': 'Comentarios',
      'excellent': 'Excelente',
      'good': 'Bueno',
      'average': 'Promedio',
      'poor': 'Pobre',
      'end_session': 'Finalizar Sesión',
      'how_was_session': '¿Cómo fue la sesión?',
      'how_was_class': '¿Cómo fue esta clase?',
      // Profile Screen
      'name': 'Nombre',
      'email': 'Correo Electrónico',
      'phone': 'Teléfono',
      'academic_year': 'Año Académico',
      'student_id': 'ID del Estudiante',
      'edit_profile': 'Editar Perfil',
      'performance': 'Desempeño',
      'accuracy': 'Precisión',
      'participation': 'Participación',
      'completion_rate': 'Tasa de Finalización',
      'session_insights': 'Perspectivas de Sesión',
      'your_questions': 'Sus Preguntas',
      'no_questions': 'Sin preguntas aún',
      'english': 'Inglés',
      'math': 'Matemáticas',
      'science': 'Ciencia',
      'history': 'Historia',
      // Ask Question Screen
      'question_title': 'Título de la Pregunta',
      'question_description': 'Descripción de la Pregunta',
      'describe_your_question': 'Describa su pregunta',
      // Settings & Dialogs
      'submit': 'Enviar',
      'cancel': 'Cancelar',
      'notifications': 'Notificaciones',
      'language': 'Idioma',
      'theme': 'Tema',
      'two_factor': 'Autenticación de Dos Factores',
      'light': 'Claro',
      'dark': 'Oscuro',
      'system': 'Sistema',
      'logout': 'Cerrar Sesión',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'choose_theme': 'Elegir Tema',
      'choose_language': 'Elegir Idioma',
      'enabled': 'Habilitado',
      'disabled': 'Deshabilitado',
      // Messages & Status
      'theme_changed': 'Tema cambiado',
      'language_changed': 'Idioma cambiado',
      'notification_enabled': 'Notificaciones habilitadas',
      'notification_disabled': 'Notificaciones deshabilitadas',
      'profile_updated': 'Perfil actualizado exitosamente',
      'password_changed': 'Contraseña cambiada exitosamente',
      'storage_cleared': 'Almacenamiento borrado',
      'logged_out': 'Sesión cerrada exitosamente',
      // Account Settings
      'account_settings': 'Configuración de Cuenta',
      'app_settings': 'Configuración de Aplicación',
      'profile_information': 'Información de Perfil',
      'edit_profile_details': 'Edite sus detalles de perfil',
      'change_password': 'Cambiar Contraseña',
      'update_password': 'Actualice su contraseña',
      'clear_cache': 'Borrar Caché',
      'clear_app_storage': 'Borrar almacenamiento y caché de la aplicación',
      'about_app': 'Acerca de la Aplicación',
      'version': 'Versión 1.0.0',
    },
    'French': {
      // Navigation & Headers
      'live_session': 'Séance en Direct',
      'student_profile': 'Profil Étudiant',
      'ask_question': 'Poser une Question',
      'settings': 'Paramètres',
      'session': 'Séance',
      'profile': 'Profil',
      'ask': 'Demander',
      'class_pulse': 'ClassPulse',
      // Join Class Screen
      'enter_code': 'Entrez le Code de Classe',
      'join_class': 'Rejoindre la Classe',
      'class_code': 'Code de Classe',
      'please_enter_code': 'Veuillez entrer un code de classe',
      'invalid_code': 'Code de classe invalide',
      // Live Session Screen
      'feedback': 'Commentaires',
      'excellent': 'Excellent',
      'good': 'Bon',
      'average': 'Moyen',
      'poor': 'Mauvais',
      'end_session': 'Terminer la Séance',
      'how_was_session': 'Comment était la séance?',
      'how_was_class': 'Comment était ce cours?',
      // Profile Screen
      'name': 'Nom',
      'email': 'Email',
      'phone': 'Téléphone',
      'academic_year': 'Année Académique',
      'student_id': 'ID Étudiant',
      'edit_profile': 'Modifier le Profil',
      'performance': 'Performance',
      'accuracy': 'Précision',
      'participation': 'Participation',
      'completion_rate': 'Taux de Complétion',
      'session_insights': 'Aperçus de Séance',
      'your_questions': 'Vos Questions',
      'no_questions': 'Pas encore de questions',
      'english': 'Anglais',
      'math': 'Mathématiques',
      'science': 'Sciences',
      'history': 'Histoire',
      // Ask Question Screen
      'question_title': 'Titre de la Question',
      'question_description': 'Description de la Question',
      'describe_your_question': 'Décrivez votre question',
      // Settings & Dialogs
      'submit': 'Soumettre',
      'cancel': 'Annuler',
      'notifications': 'Notifications',
      'language': 'Langue',
      'theme': 'Thème',
      'two_factor': 'Authentification à Deux Facteurs',
      'light': 'Clair',
      'dark': 'Sombre',
      'system': 'Système',
      'logout': 'Déconnexion',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'choose_theme': 'Choisir le Thème',
      'choose_language': 'Choisir la Langue',
      'enabled': 'Activé',
      'disabled': 'Désactivé',
      // Messages & Status
      'theme_changed': 'Thème changé',
      'language_changed': 'Langue changée',
      'notification_enabled': 'Notifications activées',
      'notification_disabled': 'Notifications désactivées',
      'profile_updated': 'Profil mis à jour avec succès',
      'password_changed': 'Mot de passe changé avec succès',
      'storage_cleared': 'Stockage effacé',
      'logged_out': 'Déconnexion réussie',
      // Account Settings
      'account_settings': 'Paramètres du Compte',
      'app_settings': 'Paramètres de l\'Application',
      'profile_information': 'Informations de Profil',
      'edit_profile_details': 'Modifiez les détails de votre profil',
      'change_password': 'Changer le Mot de Passe',
      'update_password': 'Mettez à jour votre mot de passe',
      'clear_cache': 'Effacer le Cache',
      'clear_app_storage': 'Effacer le stockage et le cache de l\'application',
      'about_app': 'À Propos de l\'Application',
      'version': 'Version 1.0.0',
    },
    'Hindi': {
      // Navigation & Headers
      'live_session': 'लाइव सत्र',
      'student_profile': 'छात्र प्रोफाइल',
      'ask_question': 'प्रश्न पूछें',
      'settings': 'सेटिंग्स',
      'session': 'सत्र',
      'profile': 'प्रोफाइल',
      'ask': 'पूछें',
      'class_pulse': 'ClassPulse',
      // Join Class Screen
      'enter_code': 'क्लास कोड दर्ज करें',
      'join_class': 'क्लास में शामिल हों',
      'class_code': 'क्लास कोड',
      'please_enter_code': 'कृपया क्लास कोड दर्ज करें',
      'invalid_code': 'अमान्य क्लास कोड',
      // Live Session Screen
      'feedback': 'प्रतिक्रिया',
      'excellent': 'उत्कृष्ट',
      'good': 'अच्छा',
      'average': 'औसत',
      'poor': 'ख़राब',
      'end_session': 'सत्र समाप्त करें',
      'how_was_session': 'सत्र कैसा था?',
      'how_was_class': 'यह क्लास कैसी थी?',
      // Profile Screen
      'name': 'नाम',
      'email': 'ईमेल',
      'phone': 'फोन',
      'academic_year': 'शैक्षणिक वर्ष',
      'student_id': 'छात्र आईडी',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'performance': 'प्रदर्शन',
      'accuracy': 'सटीकता',
      'participation': 'भागीदारी',
      'completion_rate': 'पूर्णता दर',
      'session_insights': 'सत्र अंतर्दृष्टि',
      'your_questions': 'आपके प्रश्न',
      'no_questions': 'अभी कोई प्रश्न नहीं',
      'english': 'अंग्रेजी',
      'math': 'गणित',
      'science': 'विज्ञान',
      'history': 'इतिहास',
      // Ask Question Screen
      'question_title': 'प्रश्न शीर्षक',
      'question_description': 'प्रश्न विवरण',
      'describe_your_question': 'अपना प्रश्न वर्णित करें',
      // Settings & Dialogs
      'submit': 'जमा करें',
      'cancel': 'रद्द करें',
      'notifications': 'सूचनाएं',
      'language': 'भाषा',
      'theme': 'थीम',
      'two_factor': 'दो-कारक प्रमाणीकरण',
      'light': 'हल्का',
      'dark': 'गहरा',
      'system': 'प्रणाली',
      'logout': 'लॉग आउट',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'choose_theme': 'थीम चुनें',
      'choose_language': 'भाषा चुनें',
      'enabled': 'सक्षम',
      'disabled': 'अक्षम',
      // Messages & Status
      'theme_changed': 'थीम बदल गई',
      'language_changed': 'भाषा बदल गई',
      'notification_enabled': 'सूचनाएं सक्षम',
      'notification_disabled': 'सूचनाएं अक्षम',
      'profile_updated': 'प्रोफाइल सफलतापूर्वक अपडेट किया गया',
      'password_changed': 'पासवर्ड सफलतापूर्वक बदल दिया गया',
      'storage_cleared': 'भंडारण साफ़ किया गया',
      'logged_out': 'सफलतापूर्वक लॉग आउट किया गया',
      // Account Settings
      'account_settings': 'खाता सेटिंग्स',
      'app_settings': 'ऐप सेटिंग्स',
      'profile_information': 'प्रोफाइल जानकारी',
      'edit_profile_details': 'अपनी प्रोफाइल विवरण संपादित करें',
      'change_password': 'पासवर्ड बदलें',
      'update_password': 'अपना पासवर्ड अपडेट करें',
      'clear_cache': 'कैश साफ़ करें',
      'clear_app_storage': 'ऐप भंडारण और कैश साफ़ करें',
      'about_app': 'ऐप के बारे में',
      'version': 'संस्करण 1.0.0',
    },
  };

  static String get(String language, String key) {
    return translations[language]?[key] ?? translations['English (US)']?[key] ?? key;
  }
}
